### ISSUE TITLE
take a lot of time to loop empty repeated filed

### ISSUE THREAD

**Issue by chaserchen** [googleapis/proto-plus-python#24] opened 2020-01-09 07:48 UTC
**Version:**
python 3.6.6
googleapis-common-protos  1.6.0  
proto-plus                0.4.0  
protobuf                  3.11.2

In my test, It take about 100ms to loop the empty repeated filed. It is normal on non-empty repeated filed.
**Messge example:**  
```python  
class ListVisitorsResponse(proto.Message):  
    visitors = proto.RepeatedField(proto.MESSAGE, number=1,  
        message=lpv_visitor.Visitor,  
    )  
    next_page_token = proto.Field(proto.STRING, number=2)  
    total_size = proto.Field(proto.INT32, number=3)  
```
**Test example:**
```python
>>> resp = ListVisitorsResponse(visitors=[])
>>> def test():print(time.time()); [v for v in resp.visitors]; print(time.time())
>>> test()
1578555716.0656524
1578555716.1353867
 ```
I'm very puzzled about this, can you look at it for me.

**Comment by software-dov** [comment] 2020-03-30 21:45
Tried reproducing with python 3.8.1 to no effect. Out of 1000 trials, the max iteration time was 110 microseconds, and the average 6.57 microseconds.

Closing with unable to reproduce.

**Closed by software-dov** 2020-03-30 21:45 UTC
Labels: P2, bug, can't reproduce
