### ISSUE TITLE
Provide a `from_dict` method

### ISSUE THREAD

**Issue by tswast** [googleapis/proto-plus-python#152] opened 2020-10-19 13:54 UTC
Similar to https://github.com/googleapis/proto-plus-python/issues/151, it would be quite useful to be able to parse a message from a JSON-representation dictionary.

Currently, in https://github.com/googleapis/python-bigquery/pull/332/files we need to deserialize the response to a dictionary because of how the handwritten clients are structured, but then immediately re-serialize the response to a JSON string so that we can call `from_json`.

**Comment by software-dov** [comment] 2020-10-19 15:24
Effective duplicate of #151 lumping in under that.

**Closed by software-dov** 2020-10-19 15:24 UTC

**Comment by software-dov** [comment] 2020-10-19 16:41
The message constructor allows just passing in a dict; it already does all the heavy lifting.
E.g.
```python
class Squid(proto.message):
    mass_kg = proto.Field(proto.INT32, number=1)

s = Squid({"mass_kg": 20})
```

**Comment by tswast** [comment] 2020-10-19 17:19
Does this work with nested message? I recall in the monolith it didn't work the same as the parse from dict method.

**Comment by busunkim96** [comment] 2020-10-19 21:54
@tswast It should work. This is what allows `request` to be passed as a dict to the service methods. This KMS sample has some nesting: https://github.com/googleapis/python-kms/blob/c349e3efa0b6cf5dbb9043043310ef5fac0fccc5/samples/snippets/update_key_add_rotation.py#L43-L57

**Comment by Ark-kun** [comment] 2022-12-05 01:14
> The message constructor allows just passing in a dict; it already does all the heavy lifting.

That constructor is incompatible with `message.to_dict`. Meanwhile, `.from_json` is compatible with `.to_json`

This works:
```
batch_v1.Job.from_json('{"taskGroups": [{}]}')
```
This does not work:
```
batch_v1.Job({"taskGroups": [{}]})
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-145-58ddc394e1ed> in <module>
----> 1 batch_v1.Job({"taskGroups": [{}]})

/opt/conda/lib/python3.7/site-packages/proto/message.py in __init__(self, mapping, ignore_unknown_fields, **kwargs)
    564 
    565                 raise ValueError(
--> 566                     "Unknown field for {}: {}".format(self.__class__.__name__, key)
    567                 )
    568 

ValueError: Unknown field for Job: taskGroups
```
