### ISSUE TITLE
`from_json` fails for enums fields represented as strings

### ISSUE THREAD

**Issue by busunkim96** [googleapis/proto-plus-python#81] opened 2020-07-29 22:54 UTC
```py
import proto

from google.protobuf.json_format import MessageToJson, Parse

class Squid(proto.Message):
    class Color(proto.Enum):
        RED = 0
        BLUE = 1
        GREEN = 2

    mass_kg = proto.Field(proto.INT32, number=1)
    color = proto.Field(proto.ENUM, number=2, enum=Color)

# Succeeds
blue_squid = Squid.from_json(b'{"mass_kg": 3, "color": "1"}')

# Fails
red_squid = Squid.from_json(b'{"mass_kg": 3, "color": "RED"}')
```

```
Traceback (most recent call last):
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/google/protobuf/json_format.py", line 591, in _ConvertFieldValuePair
    setattr(message, field.name, _ConvertScalarFieldValue(value, field))
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/google/protobuf/json_format.py", line 721, in _ConvertScalarFieldValue
    return _ConvertInteger(value)
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/google/protobuf/json_format.py", line 772, in _ConvertInteger
    return int(value)
ValueError: invalid literal for int() with base 10: 'RED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "proto-plus-enums.py", line 18, in <module>
    red_squid = Squid.from_json(b'{"mass_kg": 3, "color": "RED"}')
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/proto/message.py", line 349, in from_json
    Parse(payload, instance._pb)
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/google/protobuf/json_format.py", line 434, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/google/protobuf/json_format.py", line 454, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/google/protobuf/json_format.py", line 485, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/google/home/busunkim/github/python-securitycenter/samples/snippets/.nox/py-3-6/lib/python3.6/site-packages/google/protobuf/json_format.py", line 598, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse color field: invalid literal for int() with base 10: 'RED'.
```

This is problematic because protobuf seems to default to enums as strings in the JSON representation. See [`use_integers_for_enums `](https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html#google.protobuf.json_format.MessageToJson)

**Comment by busunkim96** [comment] 2020-07-29 23:02
https://github.com/googleapis/proto-plus-python/blob/405120505ae1ad6a73ecca72a02a1e9a10426f26/proto/fields.py#L90-L102 seems like the likely fix. 

`from_json` needs to be used for one sample in https://github.com/googleapis/python-securitycenter/pull/49

**Comment by busunkim96** [comment] 2020-07-29 23:55
Interestingly if I pass a dict to the constructor it will just ignore the enum

```
>>> Squid(mapping={"mass_kg": 3, "color": "RED"})
mass_kg: 3

>>> Squid(mapping={"mass_kg": 3, "color": 1})    
mass_kg: 3
color: 1
```

**Comment by busunkim96** [comment] 2020-07-30 01:04
I read the documentation on this feature in Security Command Center, and it doesn't seem like there's a way around parsing the JSON. 

You subscribe to a Pub/Sub subscription and it sends messages in JSON that you accept and convert back into a `NotificationMessage` using the library.

https://cloud.google.com/security-command-center/docs/how-to-api-manage-notifications#receive-notifications

If there's some hacky way to turn the JSON back into a message that might be alright for the time being.

**Comment by software-dov** [comment] 2020-08-07 17:55
Duplicate of #52

**Closed by software-dov** 2020-08-07 17:55 UTC
Labels: :rotating_light:, :rotating_light:, triage me
