### ISSUE TITLE
Deserialization via the Message constructor fails because of google.protobuf.struct_pb2.Value attribute

### ISSUE THREAD

**Issue by nicain** [googleapis/proto-plus-python#243] opened 2021-08-25 23:57 UTC
- Programming language: python
  - OS: macos
  - Language runtime version: python 3.9.2
  - Package version: unknown

1. Generate a `WebhookResponse` object from google.cloud.dialogflowcx_v3.types.webhook
```
from google.cloud.dialogflowcx_v3.types.webhook import WebhookResponse, PageInfo
from google.cloud.dialogflowcx_v3.types.response_message import ResponseMessage
from google.protobuf.struct_pb2 import Value


value = Value(string_value='bar')
parameter_info = PageInfo.FormInfo.ParameterInfo(display_name='foo', value=value)
form_info = PageInfo.FormInfo(parameter_info=[parameter_info])
page_info = PageInfo(form_info=form_info)
text = ResponseMessage.Text(text=['baz'])
response_message = ResponseMessage(text=text) 
messages = [response_message]
merge_behavior = WebhookResponse.FulfillmentResponse.MergeBehavior.APPEND
fulfillment_response = WebhookResponse.FulfillmentResponse(merge_behavior=merge_behavior, messages=messages)
webhook_response = WebhookResponse(fulfillment_response=fulfillment_response, page_info=page_info)
```

2. Serialize WebHookResponse to a dictionary, and then to deserialize via the Message constructor (as suggested [here](https://proto-plus-python.readthedocs.io/en/stable/messages.html#serialization))

```python
response_dict = WebhookResponse.to_dict(webhook_response)
WebhookResponse(response_dict)
```

Throws:

```
In [4]: WebhookResponse(response_dict)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-be7f63f4f5ec> in <module>
----> 1 WebhookResponse(response_dict)

~/.local/lib/python3.9/site-packages/proto/message.py in __init__(self, mapping, ignore_unknown_fields, **kwargs)
    512                 )
    513 
--> 514             pb_value = marshal.to_proto(pb_type, value)
    515             if pb_value is not None:
    516                 params[key] = pb_value

~/.local/lib/python3.9/site-packages/proto/marshal/marshal.py in to_proto(self, proto_type, value, strict)
    206         # Convert ordinary values.
    207         rule = self._rules.get(proto_type, self._noop)
--> 208         pb_value = rule.to_proto(value)
    209 
    210         # Sanity check: If we are in strict mode, did we get the value we want?

~/.local/lib/python3.9/site-packages/proto/marshal/rules/message.py in to_proto(self, value)
     30             return self._wrapper.pb(value)
     31         if isinstance(value, dict) and not self.is_map:
---> 32             return self._descriptor(**value)
     33         return value
     34 

TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.Value got str.
```

I expected this to round-trip the dictionary back to another instance of WebhookResponse, with similar structure to webhook_response.

**Comment by parthea** [comment] 2023-11-21 21:08
Closing as I cannot reproduce the issue reported in https://github.com/googleapis/proto-plus-python/issues/243#issue-979703783 using the latest version of proto-plus

```
>>> from google.cloud.dialogflowcx_v3.types.webhook import WebhookResponse, PageInfo
>>> from google.cloud.dialogflowcx_v3.types.response_message import ResponseMessage
>>> from google.protobuf.struct_pb2 import Value
>>> value = Value(string_value='bar')
>>> parameter_info = PageInfo.FormInfo.ParameterInfo(display_name='foo', value=value)
>>> form_info = PageInfo.FormInfo(parameter_info=[parameter_info])
>>> page_info = PageInfo(form_info=form_info)
>>> text = ResponseMessage.Text(text=['baz'])
>>> response_message = ResponseMessage(text=text) 
>>> messages = [response_message]
>>> merge_behavior = WebhookResponse.FulfillmentResponse.MergeBehavior.APPEND
>>> fulfillment_response = WebhookResponse.FulfillmentResponse(merge_behavior=merge_behavior, messages=messages)
>>> webhook_response = WebhookResponse(fulfillment_response=fulfillment_response, page_info=page_info)
>>> response_dict = WebhookResponse.to_dict(webhook_response)
>>> WebhookResponse(response_dict)
fulfillment_response {
  messages {
    text {
      text: "baz"
    }
  }
  merge_behavior: APPEND
}
page_info {
  form_info {
    parameter_info {
      display_name: "foo"
      value {
        string_value: "bar"
      }
    }
  }
}

>>> 
```

**Closed by parthea** 2023-11-21 21:08 UTC
Labels: type: bug, priority: p3
