### ISSUE TITLE
Public interface to access unwrapped message instances

### ISSUE THREAD

**Issue by BenRKarl** [googleapis/proto-plus-python#32] opened 2020-06-26 14:08 UTC
We're using `google.api_core.profobuf_helpers.field_mask` to generate field masks for update requests. That method won't accept a wrapped message instance from this library, raising the error:

```bash
...
pb_type = self._meta.fields[key].pb_type
KeyError: '__deepcopy__'
```

Instead we use the `message._pb` property to access the raw message instance, which isn't ideal because it's a private attribute. Another option is to use `type(message).pb()`.

Is the second approach recommended? Or is it possible to add a public interface to the wrapper class, so we could do something like `message.pb()`. I understand there's a change of a collision if the proto definition had a `pb` field so perhaps there's another possible solution.

**Comment by lukesneeringer** [comment] 2020-07-13 02:47
Yes, the `type(message).pb()` method is the recommended way.
You are also correct that the reason it is not `message.pb()` is due to collision risk. (I basically went with a hard "no collision" rule, and `pb` is defined as an _instance method on the metaclass_ to avoid the possibility.)

**Comment by lukesneeringer** [comment] 2020-07-13 02:51
@software-dov If you agree, I think this is worth fixing (with a relatively simple `except KeyError as ex: raise AttributeError(str(ex)`

**Comment by BenRKarl** [comment] 2020-07-13 14:20
@lukesneeringer was your second comment perhaps meant for this separate issue? https://github.com/googleapis/proto-plus-python/issues/31

**Comment by lukesneeringer** [comment] 2020-07-13 18:48
Yes, my second comment was intended for #31.

**Comment by BenRKarl** [comment] 2020-07-13 21:18
The issue with the recommended `type(message).pb()` is that it seems to return a different value than `message._pb` and at times doesn't play nice with other helpers, such as those for field masks and json parsing, some examples:

```py
import proto
from google.protobuf.json_format import MessageToJson
from google.api_core.profobuf_helpers import field_mask

class Foo(proto.Message):
    bar = proto.Field(proto.INT64, number=1)

foo = Foo(bar=22)

type(foo._pb)
# <class 'Foo'>
type(type(foo).pb())
# <class 'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType'>

MessageToJson(foo._pb)
# '{\n  "bar": "22"\n}'
MessageToJosn(type(foo).pb())
# TypeError: descriptor 'ListFields' of 'google.protobuf.pyext._message.CMessage' object needs an argument

field_mask(foo._pb, None)
# paths: "bar"
field_mask(type(foo).pb(), None)
# TypeError: descriptor 'Clear' of 'google.protobuf.pyext._message.CMessage' object needs an argument
```

**Comment by lukesneeringer** [comment] 2020-07-16 02:21
> The issue with the recommended type(message).pb() is that it seems to return a different value than message._pb

It literally just runs `message._pb`. Code [here](https://github.com/googleapis/proto-plus-python/blob/master/proto/message.py#L294).

> ```python
> type(type(foo).pb())
> # <class 'google.protobuf.pyext.cpp_message.GeneratedProtocolMessageType'>
> ```

The correct incantation is `type(foo).pb(foo)`. You have to explicitly pass the instance. Every other issue you are having is downstream from this one.

Obviously `type(foo).pb(foo) is non-ergonomic; if you have the message class already imported, then `Foo.pb(foo)` is much prettier.

**Comment by lukesneeringer** [comment] 2020-07-16 02:22
Note: It would be reasonable to make `google.api_core.protobuf_helpers.field_mask` smart enough to take a wrapped message.

**Comment by software-dov** [comment] 2020-07-23 21:46
Given the cleared up misunderstandings from above, do people think it would be reasonable to close this issue and open a new feature request for a field_mask method in message classes?

**Comment by BenRKarl** [comment] 2020-07-29 20:11
I confirmed that `foo._pb == type(foo).pb(foo)` and am fine to open up an issue with api core, however the spirit of the issue is to explore a more ergonomic interface than `type(foo).pb(foo)`. I'm guessing instance-level fields are a no-go because of the risk of collisions, but perhaps a more descriptive class-level method that doesn't require the instance to be passed in, something like `type(foo).get_message()`.

**Closed** 2020-08-28 18:45 UTC
Labels: type: feature request
